[package]
name = "pyext-myrustlib"
version = "0.1.0"
authors = ["Bryson Meiling <bryson.meiling@gmail.com"]

[lib]
name = "myrustlib"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]