[package]
name = "advent_of_code_2023"
version = "0.1.0"
edition = "2021"

authors = ["Bryson Meiling <bryson.meiling@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
