[package]
name = "docs_and_tests"
version = "0.1.0"
authors = ["Bryson <bryson.meiling@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
